apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: websocket-server
  namespace: websocket-app
  labels:
    app.kubernetes.io/name: websocket-server
spec:
  # Ensure at least 1 pod is always available
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: websocket-server
